import * as vscode from "vscode";
import { promises as fs } from "fs";
import * as path from "path";

const JAVA_HEADER = `/*
 * Generated by FTC Code Utils
 * Built by Team 32722
 */

`;

export function activate(context: vscode.ExtensionContext) {
    const provider = new FtcUtilsViewProvider(context.extensionUri);

    context.subscriptions.push(
        vscode.window.registerWebviewViewProvider("ftcCodeUtils", provider),
        vscode.commands.registerCommand("ftcCodeUtils.createClass", () => createJavaClass()),
        vscode.commands.registerCommand("ftcCodeUtils.createSubsystem", () => createSubsystem()),
        vscode.commands.registerCommand("ftcCodeUtils.createOpMode", () => createOpMode())
    );
}

async function getWorkspace(): Promise<string | undefined> {
    const folder = vscode.workspace.workspaceFolders?.[0];
    if (!folder) {
        vscode.window.showErrorMessage("Open an FTC project folder first.");
        return undefined;
    }
    return folder.uri.fsPath;
}

async function askName(prompt: string): Promise<string | undefined> {
    return vscode.window.showInputBox({
        prompt,
        validateInput: value => /^[A-Za-z_][A-Za-z0-9_]*$/.test(value)
            ? undefined
            : "Use a valid Java identifier."
    });
}

async function writeFile(filePath: string, content: string) {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, "utf8");
}

async function createJavaClass() {
    const workspace = await getWorkspace();
    if (!workspace) return;

    const name = await askName("Class name");
    if (!name) return;

    const packageName = await vscode.window.showInputBox({
        prompt: "Java package (optional)",
        value: "org.firstinspires.ftc.teamcode"
    });
    if (packageName === undefined) return;

    const packageLine = packageName.trim() ? `package ${packageName.trim()};\\n\\n` : "";
    const relativeDir = packageName?.trim()
        ? path.join(...packageName.trim().split("."))
        : "";

    const filePath = path.join(
        workspace,
        "TeamCode",
        "src",
        "main",
        "java",
        relativeDir,
        `${name}.java`
    );

    const content = `${JAVA_HEADER}${packageLine}public class ${name} {\\n}\\n`;
    await writeFile(filePath, content);

    const doc = await vscode.workspace.openTextDocument(filePath);
    await vscode.window.showTextDocument(doc);
    vscode.window.showInformationMessage(`Created ${name}.java`);
}

async function createSubsystem() {
    const workspace = await getWorkspace();
    if (!workspace) return;

    const name = await askName("Subsystem name");
    if (!name) return;

    const packageName = "org.firstinspires.ftc.teamcode.subsystems";
    const dir = path.join(
        workspace,
        "TeamCode",
        "src",
        "main",
        "java",
        ...packageName.split(".")
    );

    const content = `${JAVA_HEADER}package ${packageName};\\n\\npublic class ${name} {\\n\\n    public ${name}() {\\n    }\\n}\\n`;

    const filePath = path.join(dir, `${name}.java`);
    await writeFile(filePath, content);

    const doc = await vscode.workspace.openTextDocument(filePath);
    await vscode.window.showTextDocument(doc);
    vscode.window.showInformationMessage(`Created ${name} subsystem.`);
}

async function createOpMode() {
    const workspace = await getWorkspace();
    if (!workspace) return;

    const name = await askName("OpMode name");
    if (!name) return;

    const packageName = "org.firstinspires.ftc.teamcode";
    const dir = path.join(
        workspace,
        "TeamCode",
        "src",
        "main",
        "java",
        ...packageName.split(".")
    );

    const content = `${JAVA_HEADER}package ${packageName};

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;

@TeleOp(name = "${name}")
public class ${name} extends LinearOpMode {

    @Override
    public void runOpMode() throws InterruptedException {
        waitForStart();

        while (opModeIsActive()) {
        }
    }
}
`;

    const filePath = path.join(dir, `${name}.java`);
    await writeFile(filePath, content);

    const doc = await vscode.workspace.openTextDocument(filePath);
    await vscode.window.showTextDocument(doc);
    vscode.window.showInformationMessage(`Created ${name} OpMode.`);
}

class FtcUtilsViewProvider implements vscode.WebviewViewProvider {
    constructor(private readonly extensionUri: vscode.Uri) {}

    resolveWebviewView(webviewView: vscode.WebviewView) {
        webviewView.webview.options = {
            enableScripts: true
        };

        webviewView.webview.html = this.getHtml();

        webviewView.webview.onDidReceiveMessage(async message => {
            if (message.command === "createClass") {
                await vscode.commands.executeCommand("ftcCodeUtils.createClass");
            }
            if (message.command === "createSubsystem") {
                await vscode.commands.executeCommand("ftcCodeUtils.createSubsystem");
            }
            if (message.command === "createOpMode") {
                await vscode.commands.executeCommand("ftcCodeUtils.createOpMode");
            }
        });
    }

    private getHtml(): string {
        return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';">
<style>
body {
    padding: 12px;
    color: var(--vscode-foreground);
    background: var(--vscode-sideBar-background);
    font-family: var(--vscode-font-family);
}
h2 { font-size: 16px; margin-bottom: 4px; }
p { color: var(--vscode-descriptionForeground); }
button {
    width: 100%;
    padding: 8px;
    margin: 5px 0;
    border: 0;
    border-radius: 4px;
    background: var(--vscode-button-background);
    color: var(--vscode-button-foreground);
    cursor: pointer;
}
button:hover {
    background: var(--vscode-button-hoverBackground);
}
</style>
</head>
<body>
<h2>FTC Code Utils</h2>
<p>Create common FTC files with the correct structure and boilerplate.</p>

<button onclick="send('createOpMode')">Create OpMode</button>
<button onclick="send('createSubsystem')">Create Subsystem</button>
<button onclick="send('createClass')">Create Java Class</button>

<script>
const vscode = acquireVsCodeApi();
function send(command) {
    vscode.postMessage({ command });
}
</script>
</body>
</html>`;
    }
}

export function deactivate() {}